var annotated_dup =
[
    [ "hermes", null, [
      [ "cuda_utils", null, [
        [ "LaunchInfo", "structhermes_1_1cuda__utils_1_1LaunchInfo.html", "structhermes_1_1cuda__utils_1_1LaunchInfo" ],
        [ "Lock", "classhermes_1_1cuda__utils_1_1Lock.html", "classhermes_1_1cuda__utils_1_1Lock" ]
      ] ],
      [ "profiler", null, [
        [ "Profiler", "classhermes_1_1profiler_1_1Profiler.html", null ]
      ] ],
      [ "ArgParser", "classhermes_1_1ArgParser.html", "classhermes_1_1ArgParser" ],
      [ "BBox1", "classhermes_1_1BBox1.html", null ],
      [ "BBox2", "classhermes_1_1BBox2.html", null ],
      [ "BBox3", "classhermes_1_1BBox3.html", "classhermes_1_1BBox3" ],
      [ "Check", "structhermes_1_1Check.html", null ],
      [ "Circle", "classhermes_1_1Circle.html", null ],
      [ "ConsoleColors", "classhermes_1_1ConsoleColors.html", null ],
      [ "Constants", "structhermes_1_1Constants.html", null ],
      [ "ConstStrView", "classhermes_1_1ConstStrView.html", "classhermes_1_1ConstStrView" ],
      [ "CurveInterface", "classhermes_1_1CurveInterface.html", null ],
      [ "CurveRayIntersection", "structhermes_1_1CurveRayIntersection.html", "structhermes_1_1CurveRayIntersection" ],
      [ "DataTypes", "classhermes_1_1DataTypes.html", null ],
      [ "EFloat", "classhermes_1_1EFloat.html", "classhermes_1_1EFloat" ],
      [ "EnableBitMaskOperators", "structhermes_1_1EnableBitMaskOperators.html", null ],
      [ "FileSystem", "classhermes_1_1FileSystem.html", null ],
      [ "Frustum", "classhermes_1_1Frustum.html", null ],
      [ "GeometricPredicates", "structhermes_1_1GeometricPredicates.html", null ],
      [ "GeometricQueries", "structhermes_1_1GeometricQueries.html", null ],
      [ "ImplicitCircle", "classhermes_1_1ImplicitCircle.html", null ],
      [ "ImplicitCurveInterface", "classhermes_1_1ImplicitCurveInterface.html", null ],
      [ "ImplicitPlane2D", "classhermes_1_1ImplicitPlane2D.html", "classhermes_1_1ImplicitPlane2D" ],
      [ "ImplicitSphere", "classhermes_1_1ImplicitSphere.html", null ],
      [ "ImplicitSurfaceInterface", "classhermes_1_1ImplicitSurfaceInterface.html", null ],
      [ "Index2", "structhermes_1_1Index2.html", "structhermes_1_1Index2" ],
      [ "Index2Iterator", "classhermes_1_1Index2Iterator.html", "classhermes_1_1Index2Iterator" ],
      [ "Index2Range", "classhermes_1_1Index2Range.html", "classhermes_1_1Index2Range" ],
      [ "Index3", "structhermes_1_1Index3.html", "structhermes_1_1Index3" ],
      [ "Index3Iterator", "classhermes_1_1Index3Iterator.html", "classhermes_1_1Index3Iterator" ],
      [ "Index3Range", "classhermes_1_1Index3Range.html", "classhermes_1_1Index3Range" ],
      [ "Interval", "classhermes_1_1Interval.html", "classhermes_1_1Interval" ],
      [ "Line", "classhermes_1_1Line.html", "classhermes_1_1Line" ],
      [ "Line2", "classhermes_1_1Line2.html", "classhermes_1_1Line2" ],
      [ "Log", "classhermes_1_1Log.html", null ],
      [ "MathElement", "classhermes_1_1MathElement.html", null ],
      [ "Matrix2x2", "classhermes_1_1Matrix2x2.html", null ],
      [ "Matrix3x3", "classhermes_1_1Matrix3x3.html", null ],
      [ "Matrix4x4", "classhermes_1_1Matrix4x4.html", "classhermes_1_1Matrix4x4" ],
      [ "MemoryDumper", "classhermes_1_1MemoryDumper.html", null ],
      [ "Normal2", "classhermes_1_1Normal2.html", "classhermes_1_1Normal2" ],
      [ "Normal3", "classhermes_1_1Normal3.html", "classhermes_1_1Normal3" ],
      [ "Numbers", "structhermes_1_1Numbers.html", "structhermes_1_1Numbers" ],
      [ "Optional", "classhermes_1_1Optional.html", "classhermes_1_1Optional" ],
      [ "ParametricCircle", "classhermes_1_1ParametricCircle.html", "classhermes_1_1ParametricCircle" ],
      [ "ParametricCurveInterface", "classhermes_1_1ParametricCurveInterface.html", null ],
      [ "ParseTree", "classhermes_1_1ParseTree.html", "classhermes_1_1ParseTree" ],
      [ "Path", "classhermes_1_1Path.html", "classhermes_1_1Path" ],
      [ "Plane", "classhermes_1_1Plane.html", "classhermes_1_1Plane" ],
      [ "Point2", "classhermes_1_1Point2.html", "classhermes_1_1Point2" ],
      [ "Point3", "classhermes_1_1Point3.html", "classhermes_1_1Point3" ],
      [ "Quaternion", "classhermes_1_1Quaternion.html", "classhermes_1_1Quaternion" ],
      [ "Ray2", "classhermes_1_1Ray2.html", "classhermes_1_1Ray2" ],
      [ "Ray3", "classhermes_1_1Ray3.html", "classhermes_1_1Ray3" ],
      [ "Result", "classhermes_1_1Result.html", "classhermes_1_1Result" ],
      [ "Segment", "classhermes_1_1Segment.html", null ],
      [ "Shape", "classhermes_1_1Shape.html", null ],
      [ "Size2", "classhermes_1_1Size2.html", "classhermes_1_1Size2" ],
      [ "Size3", "classhermes_1_1Size3.html", "classhermes_1_1Size3" ],
      [ "Sphere", "classhermes_1_1Sphere.html", null ],
      [ "Str", "classhermes_1_1Str.html", "classhermes_1_1Str" ],
      [ "StringParser", "classhermes_1_1StringParser.html", "classhermes_1_1StringParser" ],
      [ "SurfaceInterface", "classhermes_1_1SurfaceInterface.html", null ],
      [ "SurfaceRayIntersection", "structhermes_1_1SurfaceRayIntersection.html", "structhermes_1_1SurfaceRayIntersection" ],
      [ "Timer", "classhermes_1_1Timer.html", "classhermes_1_1Timer" ],
      [ "Transform", "classhermes_1_1Transform.html", "classhermes_1_1Transform" ],
      [ "Transform2", "classhermes_1_1Transform2.html", "classhermes_1_1Transform2" ],
      [ "Trigonometry", "structhermes_1_1Trigonometry.html", null ],
      [ "UnexpectedResultType", "structhermes_1_1UnexpectedResultType.html", null ],
      [ "Vector2", "classhermes_1_1Vector2.html", "classhermes_1_1Vector2" ],
      [ "Vector3", "classhermes_1_1Vector3.html", "classhermes_1_1Vector3" ],
      [ "Vector4", "classhermes_1_1Vector4.html", "classhermes_1_1Vector4" ]
    ] ],
    [ "std", null, [
      [ "hash< hermes::Point2< T > >", "structstd_1_1hash_3_01hermes_1_1Point2_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01hermes_1_1Point2_3_01T_01_4_01_4" ],
      [ "hash< hermes::Point3< T > >", "structstd_1_1hash_3_01hermes_1_1Point3_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01hermes_1_1Point3_3_01T_01_4_01_4" ],
      [ "hash< hermes::Vector2< T > >", "structstd_1_1hash_3_01hermes_1_1Vector2_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01hermes_1_1Vector2_3_01T_01_4_01_4" ],
      [ "hash< hermes::Vector3< T > >", "structstd_1_1hash_3_01hermes_1_1Vector3_3_01T_01_4_01_4.html", "structstd_1_1hash_3_01hermes_1_1Vector3_3_01T_01_4_01_4" ]
    ] ]
];